### ISSUE TITLE
build errors with lens-4.13

### ISSUE THREAD

**Issue by DanBurton** [ekmett/lens-action#6]
I saw this error message on the stackage nightly build:

```
[4 of 4] Compiling Control.Lens.Action.Reified ( src/Control/Lens/Action/Reified.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Control/Lens/Action/Reified.o )
             
/home/dan/lens-action-0.2.0.1/src/Control/Lens/Action/Reified.hs:51:5:
    Not in scope: ‘coerce’
    Perhaps you meant ‘coerced’ (imported from Control.Lens)
             
/home/dan/lens-action-0.2.0.1/src/Control/Lens/Action/Reified.hs:51:51:
    Not in scope: ‘coerce’
    Perhaps you meant ‘coerced’ (imported from Control.Lens)
             
/home/dan/lens-action-0.2.0.1/src/Control/Lens/Action/Reified.hs:54:5:
    Not in scope: ‘coerce’
    Perhaps you meant ‘coerced’ (imported from Control.Lens)
             
/home/dan/lens-action-0.2.0.1/src/Control/Lens/Action/Reified.hs:54:46:
    Not in scope: ‘coerce’
    Perhaps you meant ‘coerced’ (imported from Control.Lens)
```

I can reproduce the same build error by building this repo via `stack test` using the following stack.yaml:

```
resolver: lts-3.11
packages:
- '.'
extra-deps:
- lens-4.13
- reflection-2.1
flags:
  lens-action:
    test-doctests: true
```
